### ISSUE TITLE
MacOS portmidi.dll

### ISSUE THREAD

**Issue by zcwaa22** [Chris-TopherW/UnityMidiPlayer#1]
Hi @Chris-TopherW I'm trying to get Unity to send Midi Out to a Behringer BCR2000, it sounds like your UnityMidiPlayer might do the trick but I'm on MacOS and the included portmidi.dll seems to be for Windows only, could you give me some pointers on what to do to get this working on a Mac? Thanks, Will

**Comment by Chris-TopherW** [comment]
Hi @zcwaa22 , take a look at the repo where I keep my modded version of port midi in c: https://github.com/Chris-TopherW/PortMidiUnity  It's a bit of a disaster but if you look for the dll building code you should be able to grab my functions and wrap them in a dynlib rather than a dll. Otherwise I'll get around to doing it myself sometime in the next few months!

**Comment by zcwaa22** [comment]
HI @Chris-TopherW Thanks for the info. I've followed the readme instructions in the pm_mac folder and am getting the following error which has got me stumped and google isn't helping, any ideas?

`Wills-iMac:PortMidiUnity-master will$ make -f pm_mac/Makefile.osx clean
rm -f *.o *~ core* */*.o */*/*.o */*~ */core* pm_test/*/pm_dll.dll 
rm -f *.opt *.ncb *.plg pm_win/Debug/pm_dll.lib pm_win/Release/pm_dll.lib
rm -f pm_test/*.opt pm_test/*.ncb
rm -f pm_java/pmjni/*.o pm_java/pmjni/*~ pm_java/*.h
rm -rf Release/CMakeFiles Debug/CMakeFiles
rm -rf pm_mac/pmdefaults/lib pm_mac/pmdefaults/src
Wills-iMac:PortMidiUnity-master will$ make -f pm_mac/Makefile.osx
rm -f CMakeCache.txt
mkdir -p Release
cd Release; cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- broken
CMake Error at /opt/local/share/cmake-3.11/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/Library/Developer/CommandLineTools/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/will/Desktop/PortMidiUnity-master/Release/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_4d920/fast"
    /Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_4d920.dir/build.make CMakeFiles/cmTC_4d920.dir/build
    Building C object CMakeFiles/cmTC_4d920.dir/testCCompiler.c.o
    /Library/Developer/CommandLineTools/usr/bin/cc   -arch i386 -arch ppc -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk   -o CMakeFiles/cmTC_4d920.dir/testCCompiler.c.o   -c /Users/will/Desktop/PortMidiUnity-master/Release/CMakeFiles/CMakeTmp/testCCompiler.c
    error: unable to create target: 'No available targets are compatible with this triple.'
    1 error generated.
    make[2]: *** [CMakeFiles/cmTC_4d920.dir/testCCompiler.c.o] Error 1
    make[1]: *** [cmTC_4d920/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:41 (PROJECT)


-- Configuring incomplete, errors occurred!
See also "/Users/will/Desktop/PortMidiUnity-master/Release/CMakeFiles/CMakeOutput.log".
See also "/Users/will/Desktop/PortMidiUnity-master/Release/CMakeFiles/CMakeError.log".`

**Comment by Chris-TopherW** [comment]
Hi @zcwaa22, sorry but I don't have the brain juice to read these error logs but I would recommend downloading port midi in its original form and trying to compile and run it on mac. If that works out then just grab my .h and C files or add the dll functions to the PM export section that extend port midi and throw them into your build. As long as they exist somewhere in your dynlib and are defined as exportable functions then the unity end should be able to stay the same
